### ISSUE TITLE
enums

### ISSUE THREAD

**Issue by wlmwlmwlm** [BenHall-7/diff-struct#1]
I like this crate. Thank you for making it.

Are you considering adding the diffing of `enum`s?

If so, would it help if I wrote a set of tests?

If so, where do I branch off, and how do I name the branch before I submit a pull request?

**Comment by benhall-7** [comment]
Hi! Sorry I didn't respond to this before, I didn't receive any email notification for it. For a while I was curious how I would support enums, but I think now I know what it would look like. This wouldn't actually require any changes on the diff-struct repo because enums would be handled on the token level. So this is doable entirely on the [diff-derive repo](https://github.com/BenHall-7/diff-derive). I had this structure in mind, was your idea similar?
```rust
enum TestEnum {
    Variant1(bool),
    Variant2 { value: u8 }
}

enum TestEnumDiff {
    Variant1(<bool as Diff>::Repr),
    Variant2 { value: <u8 as Diff>::Repr }
}

impl Diff for TestEnum {
    type Repr = TestEnumDiff;

    fn diff(&self, other: &Self) -> Self::Repr {
        match (self, other) {
            (TestEnum::Variant1(v1), TestEnum::Variant1(v2)) => {
                TestEnumDiff::Variant1(v1.diff(&v2))
            }
            (_, TestEnum::Variant1(v2)) => {
                TestEnumDiff::Variant1(<bool as Diff>::identity().diff(&v2))
            }
            (TestEnum::Variant2 { value: v1 }, TestEnum::Variant2 { value: v2 }) => {
                TestEnumDiff::Variant3 { value: v1.diff(&v2) }
            }
            (_, TestEnum::Variant2 { value: v2 } ) => {
                TestEnumDiff::Variant2 { value: <u8 as Diff>::identity().diff(&v2) }
            }
        }
    }

    fn apply(&mut self, diff: &Self::Repr) {
        todo!()
    }

    fn identity() -> Self {
        todo!()
    }
}
```

**Comment by benhall-7** [comment]
In simple terms what I'm doing is checking that the variants are the same on both enums, then diffing the two structures. When they're different, the diff is basically just the second enum only. Do you have any more suggestions on how the derive macro handles enums? I can start writing the implementation, and if you'd like to add test cases, I recommend a branch off of the master branch called "enum-tests"

**Comment by benhall-7** [comment]
@wlmwlmwlm Thanks to a contribution by [da-x](https://github.com/da-x) [here](https://github.com/BenHall-7/diff-derive/pull/1), we can close this issue. I will try to get a new version published tomorrow with the changes which will allow for enum diffs to be derived.
