### ISSUE TITLE
Implementing Debug on derived <StructName>Diff

### ISSUE THREAD

**Issue by TotalKrill** [BenHall-7/diff-struct#16]
The resulting Diff struct from using the derive macro does not implement Debug, it would be nice for, debugging...

**Comment by benhall-7** [comment]
Howdy! This is supported via the `attr` attribute on the original struct or enum, it looks like this:

```rust
#[derive(Debug, PartialEq, Diff)]
#[diff(attr(
    #[derive(Debug, PartialEq)]
))]
struct MyStruct {
    ...
}
```
