### ISSUE TITLE
Q: Store diff as string

### ISSUE THREAD

**Issue by MaMrEzO** [BenHall-7/diff-struct#2]
May I want use it to store `.diff()` as a log, how it possible?

**Comment by benhall-7** [comment]
To store the diff as a string, the easiest way is to use serde to pass the Serialize and Deserialize derive macros to the generated struct. Then you can use a json/yaml/toml/etc serializing library to create or parse the string representation. Here's an example from [this crate](https://github.com/ultimate-research/motion_lib/blob/master/src/motion_lib/mlist.rs)

```rust
#[derive(Debug, Default, Clone, PartialEq, Serialize, Deserialize, Diff)]
#[diff(attr(#[derive(Debug, Serialize, Deserialize)]))]
pub struct Motion {
    pub game_script: Hash40,
    pub flags: Flags,
    pub blend_frames: u8,
    pub animations: Vec<Animation>,
    pub scripts: Vec<Hash40>,
    pub extra: Option<Extra>,
}
```

If you want more fine-tuned control on the serde behavior for specific fields you can also pass attributes the same way on the fields of the struct above.

Of course another way to accomplish this is to just define your own function returning a string in an impl block for the diff type:

```rust
#[derive(Diff)]
struct MyType {
    value: u32,
}

impl ToString for MyTypeDiff {
    pub fn to_string(&self) -> String {
        todo()!
    }
}
```

If you want to decide whether or not to store a diff at all, I recommend just using PartialEq on the main type and checking for inequality first

**Comment by benhall-7** [comment]
Followup: the actual code to produce the diff as a string is pretty simple after. Just diff the types, plug the diff into the serializing function, and write it to whatever output you need:

```rust
fn diff_files(a: &str, b: &str, out_path: &str) -> Result<()> {
    let a = motion_lib::open(a)?;
    let b = motion_lib::open(b)?;
    let diff = a.diff(&b);
    let mut f = File::create(out_path)?;
    let pretty = to_string(&diff)?;
    f.write_all(pretty.as_bytes())?;
    Ok(())
}
```

**Comment by MaMrEzO** [comment]
Thank you for quick reply,  
Wow Rust is full of surprise, in second line of `Motion` definition `#[diff(attr(#[derive(Debug, Serialize, Deserialize)]))]` as I see this will apply to `MotionDiff`, I have another question, is there a way to do same thing for fields too(diff fields)? for example `#[serde(skip_serializing_if = "Option::is_none")]`...

**Comment by benhall-7** [comment]
I thought I implemented field attributes before in the derive macro, but unfortunately I must have left it as to-do. That seems like a good next feature to write

**Comment by benhall-7** [comment]
@MaMrEzO I've published a new version (0.4.0) with a lot of improvements. Structs now support these attributes:
`attr, visibility, name`
and these are valid on struct fields as well (except for `name` when you have a tuple struct, because tuple struct fields don't have names)

Now that you can pass attributes to the diff field, you can define something kind of like this to pass serde attributes:

```rust
#[derive(Default, PartialEq, Serialize, Diff)]
#[diff(attr(
    #[derive(Default, PartialEq, Serialize)]
))]
struct MyTestStruct {
    #[diff(attr(
        #[serde(rename = "name")]
    ))]
    test_field: u32,
}
```

Do you want to give that a try?

**Comment by MaMrEzO** [comment]
Glad to hear that. 🙌
I will, but maybe next week.

**Comment by MaMrEzO** [comment]
Sorry for being late!
I've checked it right now and I cant get it to work ...
![Screenshot_20220205_113305](https://user-images.githubusercontent.com/1070230/152633970-eac8c7a7-0158-437c-a091-e7b0807df9da.png)
may I just miss something, or I did do something wrong!

`Cargo.toml`
```toml
[package]
name = "diff-struct test"
version = "0.1.0"
authors = ["Nima-dvlp <n%%%%%%%z@gmail.com>"]
edition = "2018"

[dependencies]
diff-struct = "0.4.0"
serde = { version = "1.0.69", features = ["derive"] }
serde_json = "1.0.22"
```

`main.rs`
```rust
extern crate serde;
extern crate serde_json;
//use std::{fmt, fmt::Formatter, fmt::Result};

use diff::Diff;

#[derive(Debug, Default, PartialEq, Diff /*, Serialize*/)]
#[diff(attr(#[derive(Debug/*, Serialize, Deserialize*/)]))]
pub struct User {
    //#[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    #[diff(attr(
        #[serde(rename = "name")]
    ))]
    name: String,
    #[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    password: String,
    #[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    codes: String,
}

fn main() {
    println!("Testify: ");
    let was = User {
        name: "Ali".to_string(),
        password: "Get me to".to_string(),
        codes: "The blood code".to_string(),
    };

    let new = User {
        name: "Ali".to_string(),
        password: "Get to".to_string(),
        codes: "The bloody code".to_string(),
    };
    let diff = was.diff(&new);
    println!("{:#?}", diff);
    //println!("{:#?}", serde_json::to_string(&diff));
    //diff.password.and_then()
    println!("Handy : {:?}", diff.password);
}
```

**Comment by benhall-7** [comment]
You've pretty much got it, but a couple small things are causing problems. The reason it says it can't find the `serde` attribute is because derive macro attributes require the "parent" derive to be present, but in that case Serialize and Deserialize are commented out. And then, I think you can ignore `extern crate` syntax in 90% of cases, and just have a regular `use` statement with the derive attribute from the proper crate. I've removed some comments and things unnecessary for the example, but this compiles and outputs the expected result!

```rust
use diff::Diff;
use serde::Serialize;

#[derive(Debug, Default, PartialEq, Diff)]
#[diff(attr(#[derive(Debug, Serialize)]))]
pub struct User {
    #[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    name: String,
    #[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    password: String,
    #[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    codes: String,
}

fn main() {
    let was = User {
        name: "Ali".to_string(),
        password: "Get me to".to_string(),
        codes: "The blood code".to_string(),
    };

    let new = User {
        name: "Ali".to_string(),
        password: "Get to".to_string(),
        codes: "The bloody code".to_string(),
    };
    let diff = was.diff(&new);
    println!("{}", serde_json::to_string_pretty(&diff).unwrap());
}

```

Result:

```
{
  "password": "Get to",
  "codes": "The bloody code"
}
```

**Comment by benhall-7** [comment]
I want to leave one more hint to be aware of before I close this issue, which is that if you have a list of attributes you'd like to pass to the diff type, they should be stored consecutively within one call to `#[diff(attr(...))]` instead of multiple calls to that attribute. This is because the last one for a given field will override any previous ones. So in your example, if you want both of these to apply at once

```rust
pub struct User {
    #[diff(attr(#[serde(skip_serializing_if = "Option::is_none")]))]
    #[diff(attr(
        #[serde(rename = "name")]
    ))]
    name: String,
}
```

you would instead write this as

```rust
pub struct User {
    #[diff(attr(
        #[serde(skip_serializing_if = "Option::is_none")]
        #[serde(rename = "name")]
    ))]
    name: String,
```
