### ISSUE TITLE
Derive macro fails for structs with comments

### ISSUE THREAD

**Issue by thurn** [BenHall-7/diff-struct#6]
Attempting to apply the derive macro to 
```
/// Identifies an ability within a card.
#[derive(Diff)]
pub struct AbilityIndex(usize);
```
Produces  the compiler error `expected parentheses: #[doc(...)]`. It also fails with the same error for comments on struct fields.

Version 0.4.0.

**Comment by benhall-7** [comment]
Thanks for pointing this out, I made a bad assumption and removed a line of code that handled this explicitly. Published a new version with the fix (diff-struct: 0.4.1, and the build should display diff-derive using 0.2.1)
